### ISSUE TITLE
Support for keycloak version 13.x

### ISSUE THREAD

**Issue by hd1ex** [treydock/puppet-module-keycloak#194]
There are currently two CVEs regarding the supported keycloak versions:
- https://nvd.nist.gov/vuln/detail/CVE-2021-20222
- https://bugzilla.redhat.com/show_bug.cgi?id=1922128

I am interested in adding support for keycloak version 13. 
What has to be done or tested to support a newer version?

**Comment by treydock** [comment]
@hd1ex I have pushed #195 to begin testing this module against Keycloak 13.0.1. So far seems like all functionality will work, the tests failing for Ubuntu 20.04 are unrelated to this module.  If you want to begin using Keycloak 13 you can simply do something like this in Hiera:

```yaml
keycloak::version: '13.0.1'
```

The currently released version of this module should work just fine, since to support 13.0.1 officially was just performing updates to the module's testing matrix.
