### ISSUE TITLE
ID for Providers cannot exceed 36 characters

### ISSUE THREAD

**Issue by sifex** [treydock/puppet-module-keycloak#218]
Hey, 

I stumbled across this whilst deploying out Keycloak . When defining your `keycloak_ldap_user_provider`, or `keycloak::freeipa_user_provider`, if your `{provider-name}-{realm}` ends up being longer than 36 characters (standard UUIDv4 length), then in Keycloak version 15.0.2, it gives an error similar to the one below.

```
value too long for type character varying(36)
```

I totally get why this can occur, as the `ID` can be manually POST'ed to Keycloak for the purposes of tracking it later on. Possibly might need to re-think or adjust the `ID` to be less or equal to those number of characters, or move to a different way of tracking providers and letting the UUID self-populate.

Ideally a good solution might be to have a UUIDv4 value be deterministically generated so it can still be tracked?

**Comment by treydock** [comment]
This might be solved in #76 which I've been hesitant to merge due to how painful it could be to upgrade from previous behavior.  I've noticed warnings in my logs that the ID for users, which contains the LDAP provider ID, is invalid or not correct.  I did not realize there were restrict rules preventing something that is too long.  The default behavior with #76 would be to use IDs that are true UUIDs but they are based on a known string to generate the UUID.

There already is a function to generate consistent UUIDs, I borrowed from mcollective code I think, https://github.com/treydock/puppet-module-keycloak/blob/418648fcfac5553ad49be093ae26d974a5702161/lib/puppet/provider/keycloak_api.rb#L108

The `keycloak_ldap_user_provider` does allow overriding ID but looks like that same option isn't possible with `keycloak::freeipa_user_provider`.

I think a short-term solution will be to update `keycloak::freeipa_user_provider` to allow changing the ID of the underlying LDAP provider, or you could just use `keycloak_ldap_user_provider` and force a specific UUID.  Example of how to do this is here:  https://github.com/treydock/puppet-module-keycloak/tree/change-id#uuid-generation

Long term will be to get #76 finished and merged.

**Comment by treydock** [comment]
I released v7.11.0 that allows `keycloak::freeipa_user_provider` to have ID specified.  That is hopefully a quick work around for this issue while I decide how best to move forward with #76

**Comment by treydock** [comment]
#76 is merged and changed how the ID is generated for LDAP providers to use what Keycloak does which is generate UUID.  I'll get tag released this week or next once I've had a chance to move this through my various environments.
