### ISSUE TITLE
Init class parameter values are confusing

### ISSUE THREAD

**Issue by saz** [treydock/puppet-module-keycloak#291]
I've tried to install keycloak 22 and failed due to an old java version (still 11, which isn't supported by keycloak 22).

After checking the module, I *thought* `java_declare_method` is set to `class` but it's not :-)

May I suggest to get rid of any default values within `init.pp` (and maybe others) and instead just use hiera values? I'm happy to add a PR for that.

**Comment by treydock** [comment]
`java_declare_method` is set to `class`: 

https://github.com/treydock/puppet-module-keycloak/blob/8815e47aeb1fa51e4ce8bee97f06a96be7514170/manifests/init.pp#L217

It's quite important to have this module default to managing the Java class parameters by default as that makes this module more or less work out-of-the-box with minimal changes. It would be a challenge for both end-users using the module as well as documentation to move Java configures entirely to Hiera since this module would have to document the various values for each OS version supported and hope people did the correct things on their ends.  The defaults for the Java module will not work for Keycloak so it's really important to force newer JDKs by default.

**Comment by saz** [comment]
It's definitely not the case on Debian/Ubuntu. Look at the hiera data files in the module.

That's why I said it's confusing :)

I'm using this module on Ubuntu and need to pass newer java versions via hiera to the java class, as it's only included.

**Comment by saz** [comment]
https://github.com/treydock/puppet-module-keycloak/blob/master/data/os/Debian.yaml

**Comment by treydock** [comment]
🤔 I honestly forgot why I set that, or if it was maybe a relic from old defaults or something.  I'll do some testing with acceptance tests to see if I can move Debian and Ubuntu to default to `class`.

**Comment by treydock** [comment]
This is fixed via #295 , and will go out with this module's release of v11.0.0 once I finish Keycloak 22 support.
