### ISSUE TITLE
Upgrading Keycloak does not execute migration scripts

### ISSUE THREAD

**Issue by danifr** [treydock/puppet-module-keycloak#52]
Hi,

I just upgraded keycloak via changing the version number parameter in the module. Everything went fine but after some time running the new version, I started seeing some errors in the keycloak logs.

I'm afraid the migration scripts[1] are not run when the new version is installed.

To solve these issues, I manually ran:
```
/opt/keycloak-$KEYCLOAK_NEW_VERSION.Final/bin/jboss-cli.sh --file=/opt/keycloak-$KEYCLOAK_NEW_VERSION.Final/bin/migrate-standalone.cli
```
and:
```
[root@keycloak-dev-b11941f37c ~]# /opt/keycloak-$KEYCLOAK_NEW_VERSION/bin/jboss-cli.sh
You are disconnected at the moment. Type 'connect' to connect to the server or 'help' for the list of supported commands.
[disconnected /] connect
[standalone@localhost:9990 /] /subsystem=keycloak-server/spi=connectionsJpa/provider=default/:map-put(name=properties,key=migrationStrategy,value=update)
{
    "outcome" => "success",
    "response-headers" => {
        "operation-requires-reload" => true,
        "process-state" => "reload-required"
    }
}

[standalone@localhost:9990 /] q
```

Do you think there is a way we can integrate this in the module?
Maybe executing them for every installation (even when we install from scratch)?

Let's discuss about it. I can help you out with the MR.
Thanks,
Daniel.

[1] https://www.keycloak.org/docs/latest/upgrading/index.html

**Comment by treydock** [comment]
Because this module makes edits to standalone.xml via jboss-cli.sh it shouldn't be necessary to migrate the configs upon upgrade unless there are migrations taking place that involve more than changes to the config.  My understanding in past of the migration scripts was to support using the same standalone.xml on upgraded install but the way this module does upgrades it uses new standalone.xml for each version and just modifies it as part of the install so the starting point is that version's default standalone.xml.

The database migrations should be enabled and automatic last I checked.  Double checked and my standalone.xml already has `migrationStrategy` set to `update` and only changes made to that file are ones done by this module, everything else is default, so maybe yours was modified to not do automatic update?  The default I believe is what you added via jboss-cli.sh.

**Comment by danifr** [comment]
Hmm I'll try the upgrade procedure again when the next version of Keycloak is out.
Please keep this issue open until then :)

**Comment by cborisa** [comment]
I can confirm @treydock answer, as I use this module for updating our environment from 2.5.4 to 4.7:
- Install the new Keycloak using this module to the new path, keeping the same RDBMS connection data
- CLI file in the module will configure Keycloak to work with RDBMS and add any required changes to your keycloak install (I also include SSL configuration to the cli)
- After initial start Keycloak with update RDBMS automatically.
Standalone.xml (or standalone-ha.xml) will be already updated, as they come from the package, and CLI only adds specific parts to it.

**Comment by danifr** [comment]
Interesting. It might be my deployment then... 
I'll check again as soon as the new version of Keycloak is out. Thanks

**Comment by danifr** [comment]
I tested it again with the upgrade to keycloak 6 and I can confirm it was my configuration.

We use a little magic to have secrets within puppet manifests and this was causing the rewrite of the standalone.xml file.
